### ISSUE TITLE
How to implement parameters in a calculator

### ISSUE THREAD

**Issue by JunCEEE** [PaNOSC-ViNYL/libpyvinyl#20]
@CFGrote @shervin86 @mads-bertelsen

I think we can discuss this topic here:
Should the `Calculator` classes or `CalculatorParameters`  classes take care of parameter checks?
Maybe we also need to clarify what needs to be checked. 
https://github.com/PaNOSC-ViNYL/libpyvinyl/blob/7ebb186c6947bc4298a801f6009f07b4ddb22904/libpyvinyl/BaseCalculator.py#L43-L46

https://github.com/PaNOSC-ViNYL/libpyvinyl/blob/7ebb186c6947bc4298a801f6009f07b4ddb22904/libpyvinyl/Parameters/Collections.py#L8-L13

Obviously, there are two kinds of parameters needed for a calculator:
1. Physical parameters: wavelength, beam size, sample to detector distance, etc...
2. Calculator running parameters: how many CPU cores to use, how many snapshots would be collected, which input file to choose, etc... 

I can see the second kind can be very calculator-specific while the first kind is more general. Shall we distinguish them?

What do you think?

**Comment by JunCEEE** [comment]
One issue in my mind is how to store the detector parameters here. We are using [extra-geom](https://extra-geom.readthedocs.io/en/latest/) to handle detector geometries, but I didn't find obvious ways to store the geometry in json file. Any ideas?

**Comment by shervin86** [comment]
Physical parameters are checked by the Parameter class for valid/invalid values (inside or outside allowed intervals).
Further kind of checks, as those that involve some calculations or check physics meaning of certain configurations, should be carried on by the calculator class since it might be dependent on the calculator. 

I admit I have not thought about the parameters setting up the run of the simulation. They are somehow a special kind of parameters and they depend on the calculator + some quite common set of parameters. Still the check is on the calculator. I think that a special parameter class should be defined for this.

About the extra-geom, I have not fully understood, might be better to have a live chat about it.

**Comment by JunCEEE** [comment]
Hi @shervin86, your answer is clear to me. I'll make an appointment with you for a live chat.

**Comment by CFGrote** [comment]
The idea to subclass parameters into sth like `PhysicsParameters`, `NumericsParameters`, etc. is good.

**Comment by CFGrote** [comment]
Regarding who checks the parameters: One advantage of keeping all checks in the parameters class is that a user might want to change a parameter on an instantiated calculator. The user would then
```
calculator.parameters.parameter_key = new_value
```
If the checks were implemented in the parameters class, it would automatically be triggered by the corresponding setter method.
Otoh, the calculator would have to somehow monitor all attributes on its parameters class and run all checks if a given parameter value changes. But maybe this is now taken care of in a different way? Sorry if I miss the point.

**Comment by shervin86** [comment]
@CFGrote I get your point of triggering the check. I think that one possible solution would be:
 - having the parameter class as it is as a baseclass
 -  each calculator internally defines a derived specialized parameter class, so inheriting all the basics and re-implementing only the setters such that triggers some specific tests
 
The specialized class is then completely hidden, whenever the parameters are returned by the calculator, the baseclass is returned, no additional internal variables are added, only updated methods for checks.

Would that make sense?

**Comment by shervin86** [comment]
Outcome of the meeting with @JunCEEE 

Checking parameters
---
The syntax that we would like to support is the following:
```
# declaration of a calculator
mycalculator = FirstCalculator()
# getting default parameters initialized by the calculator
myparams = mycalculator.parameters()
# changing default values
myparams['wavelength']=4.5
# eventually print the list of parameters and their values
print(myparams)
```

The only checks performed by the parameter class is if the value is withing the allowed ranges.

More complex checks, especially those involving more parameters, should be carried on by the calculator.
The checks *cannot* be perfomed when setting the value because it would fail in case of correlated parameters. 
E.g. check if parA+parB<10, with parB=6 and parA=3
If new values are parA=9 and parB=0, when setting `parA = 9` would give an error bacause failing the condition.
So it is better to define a `check()` method for the calculators with each calculator perfoming all the checks that are required.

 - need to enforce all calculators to have a `check()` method, that returns `true` by default (not implemented), it can be done in the base class
 - specialized implementation of the `check()` method for specialized calculators needing a particular check to be carried on
 - enforce the `check()` method to be called by the `run()` method
 - suggest in the documentation to place the `check()` method where it makes sense in the code

Execution parameters
-----
Calculators should have two sets of parameters:
 - physics parameters: those related to the physics
 - execution parameters: those related on how to run the code (e.g. number of cores, splitting of the output file, path for the output file, logging level)
 
 Both are private members of the calculator class and of type `CalculatorParameters`.
A specific method to return them should be available:
 - `mycalc.parameters()`: for physics parameters
 - `mycalc.run_parameters()`: for execution parameters
Naming has not been defined, so feel free to make suggestions.


Detector geometry
----
This seems to be a tricky part.
Needs:
 - be able to load the instrument definition from the instrument database
 - be able to dump in simple text format the geometry
    - to have it versioned in the instrument repository
    - to have diff patches be added to the openPMD file in case of changes

One possible solution would be to:
 - pass the `detector_geometry` parameters as a string with the name of file defining the geometry
 - ask to add in the first block of comments of the geometry file the name of the specialized class that generated it
 - ask to implement a loader function that takes as input the path of the text file with the geometry description and reading the first block of comments instantiates and returns the right specialized geometry class

**Comment by shervin86** [comment]
Most of it implemented. Remaining considerations in a separate issue.
